In [55]:
import numpy as np
import pandas as pd

In [56]:
irisdata = pd.read_csv('Iris.csv')

In [57]:
irisdata

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [58]:
irisdata.shape

(150, 6)

In [59]:
irisdata=irisdata.drop(columns=['Id'])

In [60]:
irisdata

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [61]:
irisdata.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [63]:
irisdata['Species'].replace({'Iris-setosa':1,'Iris-versicolor':2,'Iris-virginica':3},inplace=True)

In [64]:
irisdata

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0              5.1           3.5            1.4           0.2        1
1              4.9           3.0            1.4           0.2        1
2              4.7           3.2            1.3           0.2        1
3              4.6           3.1            1.5           0.2        1
4              5.0           3.6            1.4           0.2        1
..             ...           ...            ...           ...      ...
145            6.7           3.0            5.2           2.3        3
146            6.3           2.5            5.0           1.9        3
147            6.5           3.0            5.2           2.0        3
148            6.2           3.4            5.4           2.3        3
149            5.9           3.0            5.1           1.8        3

[150 rows x 5 columns]

In [65]:
x=pd.DataFrame(irisdata,columns=['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalLengthCm']).values

In [66]:
x

array([[5.1, 3.5, 1.4, 1.4],
       [4.9, 3. , 1.4, 1.4],
       [4.7, 3.2, 1.3, 1.3],
       [4.6, 3.1, 1.5, 1.5],
       [5. , 3.6, 1.4, 1.4],
       [5.4, 3.9, 1.7, 1.7],
       [4.6, 3.4, 1.4, 1.4],
       [5. , 3.4, 1.5, 1.5],
       [4.4, 2.9, 1.4, 1.4],
       [4.9, 3.1, 1.5, 1.5],
       [5.4, 3.7, 1.5, 1.5],
       [4.8, 3.4, 1.6, 1.6],
       [4.8, 3. , 1.4, 1.4],
       [4.3, 3. , 1.1, 1.1],
       [5.8, 4. , 1.2, 1.2],
       [5.7, 4.4, 1.5, 1.5],
       [5.4, 3.9, 1.3, 1.3],
       [5.1, 3.5, 1.4, 1.4],
       [5.7, 3.8, 1.7, 1.7],
       [5.1, 3.8, 1.5, 1.5],
       [5.4, 3.4, 1.7, 1.7],
       [5.1, 3.7, 1.5, 1.5],
       [4.6, 3.6, 1. , 1. ],
       [5.1, 3.3, 1.7, 1.7],
       [4.8, 3.4, 1.9, 1.9],
       [5. , 3. , 1.6, 1.6],
       [5. , 3.4, 1.6, 1.6],
       [5.2, 3.5, 1.5, 1.5],
       [5.2, 3.4, 1.4, 1.4],
       [4.7, 3.2, 1.6, 1.6],
       [4.8, 3.1, 1.6, 1.6],
       [5.4, 3.4, 1.5, 1.5],
       [5.2, 4.1, 1.5, 1.5],
       [5.5, 4.2, 1.4, 1.4],
       [4.9, 3.1, 1.5, 1.5],
       [5. , 3.2, 1.2, 1.2],
       [5.5, 3.5, 1.3, 1.3],
       [4.9, 3.1, 1.5, 1.5],
       [4.4, 3. , 1.3, 1.3],
       [5.1, 3.4, 1.5, 1.5],
       [5. , 3.5, 1.3, 1.3],
       [4.5, 2.3, 1.3, 1.3],
       [4.4, 3.2, 1.3, 1.3],
       [5. , 3.5, 1.6, 1.6],
       [5.1, 3.8, 1.9, 1.9],
       [4.8, 3. , 1.4, 1.4],
       [5.1, 3.8, 1.6, 1.6],
       [4.6, 3.2, 1.4, 1.4],
       [5.3, 3.7, 1.5, 1.5],
       [5. , 3.3, 1.4, 1.4],
       [7. , 3.2, 4.7, 4.7],
       [6.4, 3.2, 4.5, 4.5],
       [6.9, 3.1, 4.9, 4.9],
       [5.5, 2.3, 4. , 4. ],
       [6.5, 2.8, 4.6, 4.6],
       [5.7, 2.8, 4.5, 4.5],
       [6.3, 3.3, 4.7, 4.7],
       [4.9, 2.4, 3.3, 3.3],
       [6.6, 2.9, 4.6, 4.6],
       [5.2, 2.7, 3.9, 3.9],
       [5. , 2. , 3.5, 3.5],
       [5.9, 3. , 4.2, 4.2],
       [6. , 2.2, 4. , 4. ],
       [6.1, 2.9, 4.7, 4.7],
       [5.6, 2.9, 3.6, 3.6],
       [6.7, 3.1, 4.4, 4.4],
       [5.6, 3. , 4.5, 4.5],
       [5.8, 2.7, 4.1, 4.1],
       [6.2, 2.2, 4.5, 4.5],
       [5.6, 2.5, 3.9, 3.9],
       [5.9, 3.2, 4.8, 4.8],
       [6.1, 2.8, 4. , 4. ],
       [6.3, 2.5, 4.9, 4.9],
       [6.1, 2.8, 4.7, 4.7],
       [6.4, 2.9, 4.3, 4.3],
       [6.6, 3. , 4.4, 4.4],
       [6.8, 2.8, 4.8, 4.8],
       [6.7, 3. , 5. , 5. ],
       [6. , 2.9, 4.5, 4.5],
       [5.7, 2.6, 3.5, 3.5],
       [5.5, 2.4, 3.8, 3.8],
       [5.5, 2.4, 3.7, 3.7],
       [5.8, 2.7, 3.9, 3.9],
       [6. , 2.7, 5.1, 5.1],
       [5.4, 3. , 4.5, 4.5],
       [6. , 3.4, 4.5, 4.5],
       [6.7, 3.1, 4.7, 4.7],
       [6.3, 2.3, 4.4, 4.4],
       [5.6, 3. , 4.1, 4.1],
       [5.5, 2.5, 4. , 4. ],
       [5.5, 2.6, 4.4, 4.4],
       [6.1, 3. , 4.6, 4.6],
       [5.8, 2.6, 4. , 4. ],
       [5. , 2.3, 3.3, 3.3],
       [5.6, 2.7, 4.2, 4.2],
       [5.7, 3. , 4.2, 4.2],
       [5.7, 2.9, 4.2, 4.2],
       [6.2, 2.9, 4.3, 4.3],
       [5.1, 2.5, 3. , 3. ],
       [5.7, 2.8, 4.1, 4.1],
       [6.3, 3.3, 6. , 6. ],
       [5.8, 2.7, 5.1, 5.1],
       [7.1, 3. , 5.9, 5.9],
       [6.3, 2.9, 5.6, 5.6],
       [6.5, 3. , 5.8, 5.8],
       [7.6, 3. , 6.6, 6.6],
       [4.9, 2.5, 4.5, 4.5],
       [7.3, 2.9, 6.3, 6.3],
       [6.7, 2.5, 5.8, 5.8],
       [7.2, 3.6, 6.1, 6.1],
       [6.5, 3.2, 5.1, 5.1],
       [6.4, 2.7, 5.3, 5.3],
       [6.8, 3. , 5.5, 5.5],
       [5.7, 2.5, 5. , 5. ],
       [5.8, 2.8, 5.1, 5.1],
       [6.4, 3.2, 5.3, 5.3],
       [6.5, 3. , 5.5, 5.5],
       [7.7, 3.8, 6.7, 6.7],
       [7.7, 2.6, 6.9, 6.9],
       [6. , 2.2, 5. , 5. ],
       [6.9, 3.2, 5.7, 5.7],
       [5.6, 2.8, 4.9, 4.9],
       [7.7, 2.8, 6.7, 6.7],
       [6.3, 2.7, 4.9, 4.9],
       [6.7, 3.3, 5.7, 5.7],
       [7.2, 3.2, 6. , 6. ],
       [6.2, 2.8, 4.8, 4.8],
       [6.1, 3. , 4.9, 4.9],
       [6.4, 2.8, 5.6, 5.6],
       [7.2, 3. , 5.8, 5.8],
       [7.4, 2.8, 6.1, 6.1],
       [7.9, 3.8, 6.4, 6.4],
       [6.4, 2.8, 5.6, 5.6],
       [6.3, 2.8, 5.1, 5.1],
       [6.1, 2.6, 5.6, 5.6],
       [7.7, 3. , 6.1, 6.1],
       [6.3, 3.4, 5.6, 5.6],
       [6.4, 3.1, 5.5, 5.5],
       [6. , 3. , 4.8, 4.8],
       [6.9, 3.1, 5.4, 5.4],
       [6.7, 3.1, 5.6, 5.6],
       [6.9, 3.1, 5.1, 5.1],
       [5.8, 2.7, 5.1, 5.1],
       [6.8, 3.2, 5.9, 5.9],
       [6.7, 3.3, 5.7, 5.7],
       [6.7, 3. , 5.2, 5.2],
       [6.3, 2.5, 5. , 5. ],
       [6.5, 3. , 5.2, 5.2],
       [6.2, 3.4, 5.4, 5.4],
       [5.9, 3. , 5.1, 5.1]])

In [67]:
y=irisdata.Species.values.reshape(-1,1)

In [68]:
y

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3]], dtype=int64)

In [69]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [70]:
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.30,random_state=42)

In [71]:
x_train.shape

(105, 4)

In [72]:
y_train.shape

(105, 1)

In [73]:
k=9
knclr=KNeighborsClassifier(k)

In [74]:
knclr

KNeighborsClassifier(n_neighbors=9)

In [75]:
knclr.fit(x_train,y_train)

C:\Users\mdwah\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier(n_neighbors=9)

In [76]:
y_pred=knclr.predict(x_test)

C:\Users\mdwah\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

In [77]:
metrics.accuracy_score(y_test, y_pred)*100

100.0